### ISSUE TITLE
How do I access the hipscat catalogs if I am not doing a position cross match? 

### ISSUE THREAD

**Issue by jkrick** [astronomy-commons/lsdb#416]
Hi LINCC,
I am working on a use case where i want to find the Panstarrs light curves for my favorite sample of something like 30 objects ( as a test case for scaling this up to half a million objects).  I think the overall plan is to cross match my sample with panstarrs object table to get Panstarrs objectids, and then use the Panstarrs objectids returned from the cross match to access the light curves in the Panstarrs detection table.  I have successfully followed the tutorials to do the first step and return Panstarrs objectids.  How do I do the next step of accessing the light curves given objectids?

**Comment by delucchi-cmu** [comment]
@hombit 

Do you have the radec of your objects? If so, I believe we can do that with existing join functionality. We should add something to our documentation to help users figure out how to do this! Adding Kostya, who may have a notebook that does that.

**Comment by hombit** [comment]
@jkrick I prepared a draft notebook with a possible pipeline for matching a user-defined position catalog with PS1 (both objects and detections) and plotting a few light curves. Link to notebook
https://github.com/lincc-frameworks/notebooks_lf/blob/main/ps1-snad.ipynb

Is it close to what you are doing?

**Comment by jkrick** [comment]
This is super helpful, and super fast.  Thanks @hombit & @delucchi-cmu !  

Tiny bit of feedback, I switched to using `.join` instead of `.join_nested` because I am just not on the nested bandwagon, and don't know how to deal with them (nor does my sidekick: meta AI)

Not sure if I am loading too much into this issue, but I am getting a warning about the margin cache in the hipscat that I created from my own sample, same as in the example above.  I tried putting a `margin_threshold` into my call to `.from_dataframe` but apparently that isn't the solution.  Should I put in a seperate issue asking how to properly make my own catalog with margins?  
`/opt/conda/lib/python3.11/site-packages/lsdb/dask/crossmatch_catalog_data.py:108: RuntimeWarning: Right catalog does not have a margin cache. Results may be incomplete and/or inaccurate.`

**Comment by hombit** [comment]
> Tiny bit of feedback, I switched to using .join instead of .join_nested because I am just not on the nested bandwagon, and don't know how to deal with them (nor does my sidekick: meta AI)

`nested-pandas` and `nested-dask` are the packages we developing for time-domain and spectra analysis with LSDB (so Meta has an excuse for not knowing it). I highly recommend to use it for light curves. You can find the documentation here (or ask LLM to read it for you!):
https://nested-pandas.readthedocs.io/en/latest/

We are going document it better with LSDB, but it is a relatively new thing so far.

> Not sure if I am loading too much into this issue, but I am getting a warning about the margin cache in the hipscat that I created from my own sample, same as in the example above. I tried putting a margin_threshold into my call to .from_dataframe but apparently that isn't the solution.

I believe it is an issue with PS1 catalogs you join - not your dataframe. Are you sure this issue is coming from `.crossmatch` call, not `join/join_nested` one?

**Comment by jkrick** [comment]
Yes, the margin cache error is coming from the `.crossmatch` call, and my sample is in the 'right' position in that call, so I assume it is my sample hips cat that is causing the error.  You get the same error in your sample notebook above.

**Comment by hombit** [comment]
Thank you, @jkrick, you are completely right, and it is a bug.

What happened is that margin generation happened, but margin catalog was empty. (In my notebook you can set `margin_threshold=10` which would give non-empty margin). That's why no margin is presented in a catalog, which is wrong behavior: it should assign empty margin catalog. It is the same issue as #329 we previously had for `read_hipscat`, and I create a new issue #419 for this bug.

However, since margin was empty, your results should still be fine!

**Comment by nevencaplar** [comment]
@hombit Do you think that we can close this issue?

**Comment by hombit** [comment]
I'm closing it, @jkrick feel free to reopen this issue or open a new one if you have any questions!
